//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : realisation.h
//  @ Date : 20/04/2020
//  @ Author : 
//
//


#if !defined(_REALISATION_H)
#define _REALISATION_H

#include "myAbstract.h"

class realisation : public myAbstract {
public:
	void bang();
};

#endif  //_REALISATION_H
