//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : realisation.cpp
//  @ Date : 20/04/2020
//  @ Author : 
//
//


#include "realisation.h"

void realisation::bang() {

}

